version: "2"
services:
  app:
    container_name: trackme-api
    image: trackme-api 
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
      - influx
    environment:
      - TZ=Europe/Madrid
  mongo:
    container_name: mongo
    image: mongo 
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - TZ=Europe/Madrid
  influx:
    container_name: influx
    image: influxdb 
    volumes:
      - /data/influx:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Madrid
