version: "2"
services:
  app:
    container_name: trackme-api
    image: trackme-api 
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - timescale
    environment:
      - TZ=Europe/Madrid
  timescale:
    container_name: timescale
    image: timescale/timescaledb
    volumes:
      - ./data/timescale:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ramdom_stuff
